version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme

  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
